dependencies {
    // Anvil Lib
    api(libs.anvillib)
    interfaceInjectionData(libs.anvillib.recipe)
    interfaceInjectionData(libs.anvillib.moveableEntityBlock)

    // AnvilCraft
    implementation(libs.anvilcraft) { transitive = false }
    interfaceInjectionData(libs.anvilcraft) { transitive = false }

    // Flywheel
    implementation(libs.flywheelApi)
    implementation(libs.flywheel)

    // Ponder
    implementation(libs.ponder) { transitive = false }
}
