[versions]
minecraft = "1.21.1"
neoForge = "21.1.230"
anvillib = "2.0.0+snapshot.500"
anvilcraft = "1.6.0+snapshot.2127"
flywheel = "1.0.6-beta-38"
ponder = "1.0.69"
modDevGradle = "2.0.140"
lombok = "8.7.1"

[libraries]
anvillib = { group = "dev.anvilcraft.lib", name = "anvillib-neoforge-1.21.1", version.ref = "anvillib" }
anvillib-recipe = { group = "dev.anvilcraft.lib", name = "anvillib-recipe-neoforge-1.21.1", version.ref = "anvillib" }
anvillib-moveableEntityBlock = { group = "dev.anvilcraft.lib", name = "anvillib-moveable-entity-block-neoforge-1.21.1", version.ref = "anvillib" }
anvilcraft = { group = "dev.dubhe", name = "anvilcraft-neoforge-1.21.1", version.ref = "anvilcraft" }
flywheelApi = { group = "dev.engine-room.flywheel", name = "flywheel-neoforge-api-1.21.1", version.ref = "flywheel" }
flywheel = { group = "dev.engine-room.flywheel", name = "flywheel-neoforge-1.21.1", version.ref = "flywheel" }
ponder = { group = "net.createmod.ponder", name = "Ponder-NeoForge-1.21.1", version.ref = "ponder" }

[plugins]
modDevGradle = { id = "net.neoforged.moddev", version.ref = "modDevGradle" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
